# Generated by Django 4.2 on 2025-01-20 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_remove_employee_patronymic_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
