# Generated by Django 4.2 on 2025-01-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_event_people'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarEducation',
        ),
    ]
