# Generated by Django 4.2 on 2025-01-27 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_delete_calendareducation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarskip',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='calendarvacation',
            name='employees',
        ),
        migrations.AddField(
            model_name='calendarskip',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarvacation',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
