# Generated by Django 4.2 on 2025-01-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_remove_calendarskip_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarskip',
            name='date_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarvacation',
            name='date_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
